import { useEffect, useState } from 'react';
import { Calendar, Clock, MapPin, X } from 'lucide-react';
import toast from 'react-hot-toast';
import { cancelAppointment, getAppointments } from '../../api';
import StatusBadge from '../../components/ui/StatusBadge';
import { CardSkeleton } from '../../components/ui/Skeleton';

const dateText = date => new Date(date).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric',year:'numeric'});
const BookingCard = ({ apt, onCancel, cancelling, past }) => <article className={`card overflow-hidden ${past ? 'opacity-70' : ''}`}><div className="flex flex-col gap-5 p-6 sm:flex-row sm:items-center"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-primary-100 text-primary-700"><Calendar className="h-6 w-6"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">{apt.service?.name || 'Salon appointment'}</h3><StatusBadge status={apt.status}/></div><p className="mt-1 text-sm text-ink-500">with {apt.staff?.name || 'your salon artist'}</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm text-ink-500"><span className="flex items-center gap-2"><Calendar className="h-4 w-4 text-primary-600"/>{dateText(apt.date)}</span><span className="flex items-center gap-2"><Clock className="h-4 w-4 text-primary-600"/>{apt.startTime} – {apt.endTime}</span></div></div>{!past && <button onClick={()=>onCancel(apt._id)} disabled={cancelling} className="rounded-full border border-red-200 px-4 py-2 text-sm font-bold text-red-700 hover:bg-red-50 disabled:opacity-50">{cancelling ? 'Cancelling…' : 'Cancel'}</button>}</div></article>;

export default function MyBookingsPage() {
 const [appointments,setAppointments]=useState([]),[loading,setLoading]=useState(true),[cancelling,setCancelling]=useState(null);
 const fetchAppointments=()=>getAppointments().then(r=>setAppointments(r.data)).catch(console.error).finally(()=>setLoading(false)); useEffect(()=>{fetchAppointments();},[]);
 const handleCancel=async id=>{if(!window.confirm('Cancel this appointment?')) return; setCancelling(id); try {await cancelAppointment(id);toast.success('Appointment cancelled');fetchAppointments();} catch(err){toast.error(err.response?.data?.message||'Failed to cancel');} finally{setCancelling(null);}};
 if(loading) return <main className="min-h-screen bg-champagne-50 px-5 py-16"><div className="mx-auto max-w-4xl space-y-4">{[1,2,3].map(i=><CardSkeleton key={i}/>)}</div></main>;
 const upcoming=appointments.filter(a=>['pending','confirmed'].includes(a.status)&&new Date(a.date)>=new Date(new Date().toDateString())), past=appointments.filter(a=>!upcoming.includes(a));
 return <main className="min-h-screen bg-champagne-50"><section className="bg-ink-900 px-5 py-16 text-white"><div className="mx-auto max-w-4xl"><p className="eyebrow !text-champagne-200">Your salon diary</p><h1 className="mt-3 font-display text-5xl font-bold">My bookings</h1><p className="mt-3 text-white/60">Your upcoming moments of care, all in one place.</p></div></section><div className="mx-auto max-w-4xl px-5 py-10"><section><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold">Coming up</h2><span className="text-sm text-ink-500">{upcoming.length} appointment{upcoming.length===1?'':'s'}</span></div>{upcoming.length?<div className="space-y-4">{upcoming.map(a=><BookingCard key={a._id} apt={a} onCancel={handleCancel} cancelling={cancelling===a._id}/>)}</div>:<div className="card p-10 text-center"><Calendar className="mx-auto h-8 w-8 text-primary-500"/><p className="mt-3 font-bold">Nothing booked yet</p><a href="/booking" className="mt-2 inline-block text-sm font-bold text-primary-700">Find an appointment</a></div>}</section><section className="mt-14"><h2 className="mb-5 text-lg font-bold">Past visits</h2>{past.length?<div className="space-y-4">{past.map(a=><BookingCard key={a._id} apt={a} past/>)}</div>:<div className="rounded-3xl border border-dashed border-ink-100 p-10 text-center text-sm text-ink-500">Your appointment history will appear here.</div>}</section></div></main>;
}
