import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Clock, SlidersHorizontal } from 'lucide-react';
import { getServices } from '../../api';
import { CardSkeleton } from '../../components/ui/Skeleton';

export default function ServicesPage() {
  const [services, setServices] = useState([]); const [loading, setLoading] = useState(true); const [active, setActive] = useState('All');
  useEffect(() => { getServices().then(r => setServices(r.data)).catch(console.error).finally(() => setLoading(false)); }, []);
  const categories = useMemo(() => ['All', ...new Set(services.map(s => s.category).filter(Boolean))], [services]);
  const shown = active === 'All' ? services : services.filter(s => s.category === active);
  return <main className="min-h-screen bg-champagne-50"><section className="bg-ink-900 px-5 py-20 text-white sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><p className="eyebrow !text-champagne-200">Our menu</p><h1 className="mt-3 font-display text-5xl font-bold sm:text-6xl">Beauty, your way.</h1><p className="mt-5 max-w-xl leading-7 text-white/65">Choose a little refresh, a complete transformation, or a ritual designed just for you.</p></div></section><section className="mx-auto max-w-7xl px-5 py-10 sm:px-8 lg:px-10"><div className="flex flex-col justify-between gap-5 border-b border-ink-100 pb-7 sm:flex-row sm:items-center"><div className="flex items-center gap-2 text-sm font-bold"><SlidersHorizontal className="h-4 w-4 text-primary-600"/> Browse treatments</div><div className="flex gap-2 overflow-x-auto pb-1">{categories.map(category=><button key={category} onClick={()=>setActive(category)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold transition ${active === category ? 'bg-ink-900 text-white' : 'bg-white text-ink-500 hover:bg-primary-100'}`}>{category}</button>)}</div></div>{loading ? <div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{[1,2,3,4,5,6].map(i=><CardSkeleton key={i}/>)}</div> : shown.length ? <div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{shown.map(service=><article key={service._id} className="card flex min-h-[260px] flex-col p-7"><div className="flex items-start justify-between"><span className="eyebrow">{service.category}</span><span className="font-display text-3xl font-bold text-primary-700">Rs {service.price}</span></div><h2 className="mt-8 text-xl font-bold">{service.name}</h2><p className="mt-3 flex-1 text-sm leading-6 text-ink-500">{service.description}</p><div className="mt-6 flex items-center justify-between border-t border-ink-100 pt-4"><span className="flex items-center gap-2 text-sm text-ink-500"><Clock className="h-4 w-4"/>{service.durationMinutes} min</span><Link to="/booking" className="rounded-full bg-primary-100 px-4 py-2 text-sm font-bold text-primary-700 hover:bg-primary-200">Book <ArrowRight className="inline h-4 w-4"/></Link></div></article>)}</div> : <p className="py-20 text-center text-ink-500">No services in this category yet.</p>}</section></main>;
}
